---
- name: Perform Health Check of Ansible Automation Platform
  hosts: localhost
  gather_facts: false
  become: false

  vars_files:
    - vars/main.yml

  tasks:
    - name: Perform Health Checks
      ansible.builtin.include_tasks:
        file: tasks/health_check.yml
        apply:
          tags: health_check

    - name: Generate Report
      ansible.builtin.include_tasks:
        file: tasks/report.yml
        apply:
          tags: report

    - name: Configure Nginx
      vars:
        nginx_server_name: "{{ lookup('ansible.builtin.env', 'NGINX_SERVER_NAME') }}"
      ansible.builtin.include_tasks:
        file: tasks/nginx.yml
        apply:
          tags: nginx
